### ISSUE TITLE
Live editing of the navmesh from srcds

### ISSUE THREAD

**Issue by besenyei** [Dadido3/AzBot#7]
It would be convenient for clients to have live editing ability of the navmesh currently running on the server instance, so they can make adjustments on the fly and save updates, rather than going into a singleplayer/local server to edit a navmesh and then upload to the server.

**Comment by Dadido3** [comment]
What stops you from using the editing commands on a SRCDS? As long as you have ULX installed, and you  have access to the commands, you can just edit navmeshes live like in singleplayer.

**Comment by besenyei** [comment]
ah, I had assumed the capability was missing, I'll check again, if it is due to user error, I apologize.
